// SPDX-FileCopyrightText: 2025-2026 SPHARX Ltd.
// SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0

#include "airy_memory.h"
#include "error.h"
/*
 * P0.18.1: daemon_main.h transitively provides atomic_compat,
 * daemon_bootstrap_sd/ipc, daemon_cupolas, daemon_platform_ext, logging,
 * svc_logger headers. This daemon uses a custom airy_event_loop and a
 * collector thread; it does not use the JSON-RPC boilerplate generated by
 * DAEMON_DECLARE_COMMON.
 */

#include "airy_event_loop.h"
#include "daemon_main.h"
#include "platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef _WIN32
#ifdef __linux__
#include <sys/sysinfo.h>
#endif
#include <sys/statvfs.h>
#include <sys/utsname.h>
#include <unistd.h>
#ifdef __APPLE__
#include <sys/sysctl.h>
#include <sys/time.h>
#include <mach/mach.h>
#endif
#endif

#define INFO_D_DEFAULT_PORT 8083
#define INFO_D_MAX_BUFFER 65536
#define INFO_D_DEFAULT_SOCKET airy_runtime_dir_socket("info.sock")
#define INFO_D_COLLECT_INTERVAL_SEC 5
#define INFO_D_HISTORY_SIZE 64

typedef struct {
    double cpu_usage_pct;
    uint64_t total_memory_kb;
    uint64_t free_memory_kb;
    uint64_t used_memory_kb;
    double memory_usage_pct;
    uint64_t disk_total_kb;
    uint64_t disk_free_kb;
    uint64_t disk_used_kb;
    double disk_usage_pct;
    int cpu_cores;
    uint64_t uptime_sec;
    uint64_t timestamp;
} system_info_snapshot_t;

typedef struct {
    airy_sock_t server_fd;
    airy_mtx_t lock;
    airy_thread_t collect_thread;
    atomic_int running;
    atomic_int collect_running;
    atomic_int force_stop;
    uint64_t start_time;
    uint64_t request_count;
    uint64_t error_count;
    uint64_t last_collect_time;
    system_info_snapshot_t latest_snapshot;
    system_info_snapshot_t history[INFO_D_HISTORY_SIZE];
    size_t history_count;
    size_t history_head;
    int tcp_port;
    char *socket_path;
} info_d_service_t;

static info_d_service_t g_service = {0};
static atomic_int g_shutdown = 0;
static airy_event_loop_t *g_event_loop = NULL;
static daemon_bootstrap_sd_t *g_bsd = NULL;
static daemon_bootstrap_ipc_t *g_bipc = NULL;

static void info_d_signal_handler(int sig)
{
    (void)sig;

    atomic_store_explicit(&g_shutdown, 1, memory_order_seq_cst);
    if (g_event_loop)
        airy_event_loop_stop_async(g_event_loop);
#ifndef _WIN32
    {
        static const char sig_msg[] =
            "[SIG] shutdown signal received, initiating graceful shutdown\n";
        (void)write(STDERR_FILENO, sig_msg, sizeof(sig_msg) - 1);
    }
#endif
}

static void svc_log_toggle_handler(int sig)
{
    (void)sig;
    static int debug_mode = 0;
    debug_mode = !debug_mode;
    log_set_module_level("*", debug_mode ? LOG_LEVEL_DEBUG : LOG_LEVEL_INFO);
}

static void info_d_handle_request(info_d_service_t *svc, airy_sock_t client_fd);

static int info_d_on_client(int fd, uint32_t events, void *user_data)
{
    (void)events;
    info_d_service_t *svc = (info_d_service_t *)user_data;
    if (!svc || !svc->running) {
        AIRY_ERROR(AIRY_ERR_INVALID_PARAM, "svc is NULL or not running");
    }

    airy_sock_t client = airy_sock_accept(fd, 0);
    if (client != AIRY_INVALID_SOCKET) {
        info_d_handle_request(svc, client);
    }
    return 0;
}

static int info_d_collect_system_info(system_info_snapshot_t *snap)
{
    if (!snap) {
        AIRY_ERROR(AIRY_ERR_INVALID_PARAM, "snap is NULL");
    }
    __builtin_memset(snap, 0, sizeof(*snap));
    snap->timestamp = (uint64_t)time(NULL);

#ifdef _WIN32
    SYSTEM_INFO sys_info;
    GetSystemInfo(&sys_info);
    snap->cpu_cores = (int)sys_info.dwNumberOfProcessors;

    MEMORYSTATUSEX mem_status;
    mem_status.dwLength = sizeof(mem_status);
    if (GlobalMemoryStatusEx(&mem_status)) {
        snap->total_memory_kb = (uint64_t)(mem_status.ullTotalPhys / 1024);
        snap->free_memory_kb = (uint64_t)(mem_status.ullAvailPhys / 1024);
        snap->used_memory_kb = snap->total_memory_kb - snap->free_memory_kb;
        if (snap->total_memory_kb > 0)
            snap->memory_usage_pct =
                (double)snap->used_memory_kb / (double)snap->total_memory_kb * 100.0;
    }

    ULARGE_INTEGER total_bytes, free_bytes, avail_bytes;
    if (GetDiskFreeSpaceExW(L"C:\\", &avail_bytes, &total_bytes, &free_bytes)) {
        snap->disk_total_kb = (uint64_t)(total_bytes.QuadPart / 1024);
        snap->disk_free_kb = (uint64_t)(free_bytes.QuadPart / 1024);
        snap->disk_used_kb = snap->disk_total_kb - snap->disk_free_kb;
        if (snap->disk_total_kb > 0)
            snap->disk_usage_pct = (double)snap->disk_used_kb / (double)snap->disk_total_kb * 100.0;
    }
#else
    long nproc = sysconf(_SC_NPROCESSORS_ONLN);
    snap->cpu_cores = (int)(nproc > 0 ? nproc : 1);

#ifdef __APPLE__
    /* macOS: sysctl for physical memory, host_statistics for free pages,
     * KERN_BOOTTIME for uptime (no sysinfo(2) on macOS). */
    int mib[2] = {CTL_HW, HW_MEMSIZE};
    int64_t memsize = 0;
    size_t len = sizeof(memsize);
    if (sysctl(mib, 2, &memsize, &len, NULL, 0) == 0 && memsize > 0)
        snap->total_memory_kb = (uint64_t)(memsize / 1024);

    vm_size_t page_size = 0;
    mach_msg_type_number_t cnt = HOST_VM_INFO64_COUNT;
    vm_statistics64_data_t vm_stat;
    mach_port_t host = mach_host_self();
    if (host_statistics64(host, HOST_VM_INFO64, (host_info64_t)&vm_stat, &cnt) ==
            KERN_SUCCESS &&
        host_page_size(host, &page_size) == KERN_SUCCESS) {
        uint64_t free_pages = vm_stat.free_count + vm_stat.inactive_count;
        snap->free_memory_kb = free_pages * page_size / 1024;
    }
    mach_port_deallocate(mach_task_self(), host);
    snap->used_memory_kb = snap->total_memory_kb - snap->free_memory_kb;
    if (snap->total_memory_kb > 0)
        snap->memory_usage_pct =
            (double)snap->used_memory_kb / (double)snap->total_memory_kb * 100.0;

    struct timeval boottime, now;
    len = sizeof(boottime);
    mib[0] = CTL_KERN;
    mib[1] = KERN_BOOTTIME;
    if (sysctl(mib, 2, &boottime, &len, NULL, 0) == 0 &&
        gettimeofday(&now, NULL) == 0 && now.tv_sec >= boottime.tv_sec)
        snap->uptime_sec = (uint64_t)(now.tv_sec - boottime.tv_sec);
#else
    struct sysinfo si;
    if (sysinfo(&si) == 0) {
        snap->total_memory_kb = (uint64_t)(si.totalram / 1024);
        snap->free_memory_kb = (uint64_t)(si.freeram / 1024);
        snap->used_memory_kb = snap->total_memory_kb - snap->free_memory_kb;
        if (snap->total_memory_kb > 0)
            snap->memory_usage_pct =
                (double)snap->used_memory_kb / (double)snap->total_memory_kb * 100.0;
        snap->uptime_sec = (uint64_t)si.uptime;
    }
#endif

    struct statvfs vfs;
    if (statvfs("/", &vfs) == 0) {
        snap->disk_total_kb = (uint64_t)(vfs.f_blocks * vfs.f_frsize / 1024);
        snap->disk_free_kb = (uint64_t)(vfs.f_bfree * vfs.f_frsize / 1024);
        snap->disk_used_kb = snap->disk_total_kb - snap->disk_free_kb;
        if (snap->disk_total_kb > 0)
            snap->disk_usage_pct = (double)snap->disk_used_kb / (double)snap->disk_total_kb * 100.0;
    }

    long clk_tck = sysconf(_SC_CLK_TCK);
    if (clk_tck <= 0)
        clk_tck = 100;
    snap->cpu_usage_pct = 0.0;
#endif

    return 0;
}

static void info_d_history_append(info_d_service_t *svc, const system_info_snapshot_t *snap)
{
    svc->history[svc->history_head] = *snap;
    svc->history_head = (svc->history_head + 1) % INFO_D_HISTORY_SIZE;
    if (svc->history_count < INFO_D_HISTORY_SIZE)
        svc->history_count++;
}

#ifdef _WIN32
static DWORD WINAPI info_d_collect_loop(LPVOID arg)
{
#else
static void *info_d_collect_loop(void *arg)
{
#endif
    info_d_service_t *svc = (info_d_service_t *)arg;
    if (!svc) {
#ifdef _WIN32
        return EXIT_FAILURE;
#else
        AIRY_ERROR_NULL(AIRY_ERR_INVALID_PARAM, "null parameter");
#endif
    }

    while (svc->collect_running) {
        system_info_snapshot_t snap;
        info_d_collect_system_info(&snap);

        airy_mtx_lock(&svc->lock);
        __builtin_memcpy(&svc->latest_snapshot, &snap, sizeof(snap));
        svc->last_collect_time = snap.timestamp;
        info_d_history_append(svc, &snap);
        airy_mtx_unlock(&svc->lock);

        for (int i = 0; i < INFO_D_COLLECT_INTERVAL_SEC && svc->collect_running; i++) {
#ifdef _WIN32
            Sleep(1000);
#else
            sleep(1);
#endif
        }
    }

#ifdef _WIN32
    return 0;
#else
    return NULL;
#endif
}

static int info_d_init(info_d_service_t *svc, int port, const char *sock)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

    __builtin_memset(svc, 0, sizeof(*svc));
    svc->tcp_port = port > 0 ? port : INFO_D_DEFAULT_PORT;
    svc->socket_path = sock ? AIRY_STRDUP(sock) : AIRY_STRDUP(INFO_D_DEFAULT_SOCKET);
    svc->start_time = (uint64_t)time(NULL);

    airy_mtx_init(&svc->lock);
    airy_sock_init();

    info_d_collect_system_info(&svc->latest_snapshot);
    svc->last_collect_time = svc->latest_snapshot.timestamp;

    SVC_LOG_INFO("info_d: init complete (cpu_cores=%d)", svc->latest_snapshot.cpu_cores);
    return AIRY_SUCCESS;
}

static int info_d_start(info_d_service_t *svc)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

#ifndef _WIN32
    svc->server_fd = airy_sock_create_unix_server(svc->socket_path);
    if (svc->server_fd < 0) {
        SVC_LOG_ERROR("info_d: failed to create socket at %s", svc->socket_path);
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to create unix socket");
    }
#else
    svc->server_fd = airy_sock_create_tcp_server("127.0.0.1", (uint16_t)svc->tcp_port);
    if (svc->server_fd < 0) {
        SVC_LOG_ERROR("info_d: failed to create TCP server");
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to create TCP server");
    }
#endif

    svc->running = 1;
    svc->collect_running = 1;
    svc->force_stop = 0;

    airy_thread_create(&svc->collect_thread, info_d_collect_loop, svc);

    SVC_LOG_INFO("info_d: service started (collect_interval=%ds)", INFO_D_COLLECT_INTERVAL_SEC);
    return AIRY_SUCCESS;
}

static int info_d_stop(info_d_service_t *svc, int force)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

    airy_mtx_lock(&svc->lock);
    svc->running = 0;
    svc->collect_running = 0;
    if (force)
        svc->force_stop = 1;
    airy_mtx_unlock(&svc->lock);

    if (force) {
        airy_thread_join(svc->collect_thread, NULL);
    } else {
        airy_thread_join(svc->collect_thread, NULL);
    }

    if (svc->server_fd != AIRY_INVALID_SOCKET) {
        airy_sock_close(svc->server_fd);
        svc->server_fd = AIRY_INVALID_SOCKET;
    }

    if (force) {
#ifndef _WIN32
        unlink(svc->socket_path);
#endif
    }

    SVC_LOG_INFO("info_d: service stopped (force=%d, collections=%zu)", force, svc->history_count);
    return AIRY_SUCCESS;
}

static int info_d_destroy(info_d_service_t *svc)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

    if (svc->server_fd != AIRY_INVALID_SOCKET) {
        airy_sock_close(svc->server_fd);
    }
    airy_sock_cleanup();
    airy_mtx_destroy(&svc->lock);
    AIRY_FREE(svc->socket_path);
    __builtin_memset(svc, 0, sizeof(*svc));
    SVC_LOG_INFO("info_d: service destroyed");
    return AIRY_SUCCESS;
}

static uint64_t info_d_healthcheck(info_d_service_t *svc)
{
    if (!svc)
        return 0;

    uint64_t last_time = 0;
    airy_mtx_lock(&svc->lock);
    last_time = svc->last_collect_time;
    airy_mtx_unlock(&svc->lock);

    if (!svc->running)
        return 0;

    uint64_t now = (uint64_t)time(NULL);
    uint64_t staleness = now > last_time ? now - last_time : 0;
    if (staleness > (uint64_t)(INFO_D_COLLECT_INTERVAL_SEC * 3))
        return 0;

    return last_time;
}

/* ==================== L2 namespace methods (02-l2-service-protocol.md §5/§6)
 * ====================
 * gateway_d strips the "<daemon>." prefix during forwarding, so method names
 * here carry no prefix.
 */

static cJSON *info_d_build_snapshot_json(const system_info_snapshot_t *snap)
{
    cJSON *item = cJSON_CreateObject();
    cJSON_AddNumberToObject(item, "timestamp", (double)snap->timestamp);
    cJSON_AddNumberToObject(item, "cpu_cores", snap->cpu_cores);
    cJSON_AddNumberToObject(item, "cpu_usage_pct", snap->cpu_usage_pct);
    cJSON_AddNumberToObject(item, "total_memory_kb", (double)snap->total_memory_kb);
    cJSON_AddNumberToObject(item, "free_memory_kb", (double)snap->free_memory_kb);
    cJSON_AddNumberToObject(item, "used_memory_kb", (double)snap->used_memory_kb);
    cJSON_AddNumberToObject(item, "memory_usage_pct", snap->memory_usage_pct);
    cJSON_AddNumberToObject(item, "disk_total_kb", (double)snap->disk_total_kb);
    cJSON_AddNumberToObject(item, "disk_free_kb", (double)snap->disk_free_kb);
    cJSON_AddNumberToObject(item, "disk_used_kb", (double)snap->disk_used_kb);
    cJSON_AddNumberToObject(item, "disk_usage_pct", snap->disk_usage_pct);
    cJSON_AddNumberToObject(item, "uptime_sec", (double)snap->uptime_sec);
    return item;
}

static cJSON *info_d_build_system_result(info_d_service_t *svc)
{
    airy_mtx_lock(&svc->lock);
    system_info_snapshot_t snap = svc->latest_snapshot;
    airy_mtx_unlock(&svc->lock);

    const char *platform_name = "Linux";
    const char *hostname = "localhost";
    const char *kernel_release = "unknown";
#ifndef _WIN32
    struct utsname uts;
    if (uname(&uts) == 0) {
        platform_name = uts.sysname;
        hostname = uts.nodename;
        kernel_release = uts.release;
    }
#endif

    cJSON *result = cJSON_CreateObject();
    cJSON_AddStringToObject(result, "service", "info_d");
    cJSON_AddStringToObject(result, "platform", platform_name);
    cJSON_AddStringToObject(result, "hostname", hostname);
    cJSON_AddStringToObject(result, "kernel_version", kernel_release);
    cJSON_AddItemToObject(result, "system", info_d_build_snapshot_json(&snap));
    return result;
}

static cJSON *info_d_build_history_result(info_d_service_t *svc, cJSON *params)
{

    int limit = INFO_D_HISTORY_SIZE;
    if (cJSON_IsObject(params)) {
        cJSON *n = cJSON_GetObjectItem(params, "N");
        if (!cJSON_IsNumber(n))
            n = cJSON_GetObjectItem(params, "n");
        if (!cJSON_IsNumber(n))
            n = cJSON_GetObjectItem(params, "count");
        if (!cJSON_IsNumber(n))
            n = cJSON_GetObjectItem(params, "limit");
        if (cJSON_IsNumber(n))
            limit = n->valueint;
    } else if (cJSON_IsArray(params) && cJSON_GetArraySize(params) > 0) {
        cJSON *n = cJSON_GetArrayItem(params, 0);
        if (cJSON_IsNumber(n))
            limit = n->valueint;
    }
    if (limit < 0)
        limit = 0;
    if (limit > (int)INFO_D_HISTORY_SIZE)
        limit = (int)INFO_D_HISTORY_SIZE;

    airy_mtx_lock(&svc->lock);
    size_t take = svc->history_count < (size_t)limit ? svc->history_count : (size_t)limit;
    size_t head = svc->history_head;

    cJSON *arr = cJSON_CreateArray();

    for (size_t i = 0; i < take; i++) {
        size_t idx = (head + INFO_D_HISTORY_SIZE - take + i) % INFO_D_HISTORY_SIZE;
        cJSON_AddItemToArray(arr, info_d_build_snapshot_json(&svc->history[idx]));
    }
    airy_mtx_unlock(&svc->lock);
    return arr;
}

static cJSON *info_d_build_health_result(info_d_service_t *svc)
{
    airy_mtx_lock(&svc->lock);
    int collecting = atomic_load_explicit(&svc->collect_running, memory_order_relaxed);
    int running = atomic_load_explicit(&svc->running, memory_order_relaxed);
    uint64_t last_collect = svc->last_collect_time;
    airy_mtx_unlock(&svc->lock);

    uint64_t now = (uint64_t)time(NULL);
    uint64_t uptime_s = now > svc->start_time ? now - svc->start_time : 0;
    uint64_t staleness = now > last_collect ? now - last_collect : 0;
    const char *status =
        (collecting && running && staleness <= (uint64_t)(INFO_D_COLLECT_INTERVAL_SEC * 3)) ?
            "ok" :
            "degraded";

    cJSON *result = cJSON_CreateObject();
    cJSON_AddStringToObject(result, "status", status);
    cJSON_AddStringToObject(result, "service", "info_d");
    cJSON_AddBoolToObject(result, "collecting", collecting ? 1 : 0);
    cJSON_AddBoolToObject(result, "running", running ? 1 : 0);
    cJSON_AddNumberToObject(result, "last_collect_time", (double)last_collect);
    cJSON_AddNumberToObject(result, "staleness_sec", (double)staleness);
    cJSON_AddNumberToObject(result, "uptime_s", (double)uptime_s);
    cJSON_AddNumberToObject(result, "timestamp", (double)now);
    return result;
}

static void handle_system(info_d_service_t *svc, cJSON *params, int id, airy_sock_t client_fd)
{
    (void)params;
    cJSON *result = info_d_build_system_result(svc);
    JSONRPC_SEND_SUCCESS(client_fd, result, id);
}

static void handle_history(info_d_service_t *svc, cJSON *params, int id, airy_sock_t client_fd)
{
    cJSON *result = info_d_build_history_result(svc, params);
    JSONRPC_SEND_SUCCESS(client_fd, result, id);
}

static void handle_health(info_d_service_t *svc, cJSON *params, int id, airy_sock_t client_fd)
{
    (void)params;
    cJSON *result = info_d_build_health_result(svc);
    JSONRPC_SEND_SUCCESS(client_fd, result, id);
}

static void info_d_handle_request(info_d_service_t *svc, airy_sock_t client_fd)
{
    char buffer[INFO_D_MAX_BUFFER];
#ifndef _WIN32
    /* Wait for request data to be ready before recv: airy_sock_recv is a
     * non-blocking MSG_DONTWAIT read; recv immediately after accept returns 0
     * on EAGAIN and would misjudge the connection as failed and close it (RPC
     * timing race). */
    struct pollfd pfd;
    pfd.fd = (int)client_fd;
    pfd.events = POLLIN;
    pfd.revents = 0;
    int pr = poll(&pfd, 1, 5000);
    if (pr <= 0 || !(pfd.revents & POLLIN)) {
        airy_sock_close(client_fd);
        return;
    }
#endif
    ssize_t n = airy_sock_recv(client_fd, buffer, sizeof(buffer) - 1);
    if (n <= 0) {
        airy_sock_close(client_fd);
        return;
    }
    buffer[n] = '\0';

    /* L2 standard methods <ns>.shutdown / <ns>.get_stats
     * (02-l2-service-protocol.md §6.1): first try to parse the JSON-RPC
     * request; on a standard-method hit, respond per JSON-RPC 2.0 and return;
     * all other requests keep the original logic, backward compatible. */
    cJSON *req = cJSON_Parse(buffer);
    if (req) {
        cJSON *m = cJSON_GetObjectItem(req, "method");
        cJSON *idj = cJSON_GetObjectItem(req, "id");
        if (cJSON_IsString(m) && idj) {
            int rid = cJSON_IsNumber(idj) ? idj->valueint : 0;
            if (strcmp(m->valuestring, "shutdown") == 0) {

                atomic_store_explicit(&g_shutdown, 1, memory_order_seq_cst);
                cJSON *result = cJSON_CreateObject();
                cJSON_AddStringToObject(result, "status", "shutting_down");
                JSONRPC_SEND_SUCCESS(client_fd, result, rid);
                cJSON_Delete(req);
                airy_sock_close(client_fd);
                return;
            } else if (strcmp(m->valuestring, "get_stats") == 0) {
                airy_mtx_lock(&svc->lock);
                uint64_t requests = svc->request_count;
                uint64_t errors = svc->error_count;
                size_t hcount = svc->history_count;
                airy_mtx_unlock(&svc->lock);
                uint64_t uptime = (uint64_t)time(NULL) - svc->start_time;
                cJSON *result = cJSON_CreateObject();
                cJSON_AddStringToObject(result, "daemon", "info_d");
                cJSON_AddNumberToObject(result, "uptime_s", (double)uptime);
                cJSON_AddNumberToObject(result, "requests", (double)requests);
                cJSON_AddNumberToObject(result, "errors", (double)errors);
                cJSON_AddNumberToObject(result, "history_count", (double)hcount);
                JSONRPC_SEND_SUCCESS(client_fd, result, rid);
                cJSON_Delete(req);
                airy_sock_close(client_fd);
                return;
            } else if (strcmp(m->valuestring, "health_check") == 0) {
                uint64_t uptime = (uint64_t)time(NULL) - svc->start_time;
                cJSON *result = cJSON_CreateObject();
                cJSON_AddStringToObject(result, "status", "ok");
                cJSON_AddStringToObject(result, "service", "info_d");
                cJSON_AddNumberToObject(result, "uptime_s", (double)uptime);
                cJSON_AddNumberToObject(result, "timestamp", (double)time(NULL) * 1000.0);
                JSONRPC_SEND_SUCCESS(client_fd, result, rid);
                cJSON_Delete(req);
                airy_sock_close(client_fd);
                return;
            } else if (strcmp(m->valuestring, "system") == 0) {
                cJSON *params = cJSON_GetObjectItem(req, "params");
                handle_system(svc, params, rid, client_fd);
                cJSON_Delete(req);
                airy_sock_close(client_fd);
                return;
            } else if (strcmp(m->valuestring, "history") == 0) {
                cJSON *params = cJSON_GetObjectItem(req, "params");
                handle_history(svc, params, rid, client_fd);
                cJSON_Delete(req);
                airy_sock_close(client_fd);
                return;
            } else if (strcmp(m->valuestring, "health") == 0) {
                cJSON *params = cJSON_GetObjectItem(req, "params");
                handle_health(svc, params, rid, client_fd);
                cJSON_Delete(req);
                airy_sock_close(client_fd);
                return;
            }
        }
        cJSON_Delete(req);
    }

    airy_mtx_lock(&svc->lock);
    svc->request_count++;
    system_info_snapshot_t snap = svc->latest_snapshot;
    airy_mtx_unlock(&svc->lock);

    char response[8192];
#ifdef _WIN32
    const char *platform_name = "Windows";
#else
    struct utsname uts;
    const char *platform_name = "Linux";
    if (uname(&uts) == 0) {
        platform_name = uts.sysname;
    }
#endif

    uint64_t service_uptime = (uint64_t)time(NULL) - svc->start_time;
    uint64_t last_collect = info_d_healthcheck(svc);

    snprintf(response, sizeof(response),
             "{"
             "\"service\":\"info_d\","
             "\"status\":\"ok\","
             "\"platform\":\"%s\","
             "\"service_uptime_sec\":%llu,"
             "\"requests\":%llu,"
             "\"errors\":%llu,"
             "\"healthy\":%s,"
             "\"system\":{"
             "\"cpu_cores\":%d,"
             "\"cpu_usage_pct\":%.2f,"
             "\"total_memory_kb\":%llu,"
             "\"free_memory_kb\":%llu,"
             "\"used_memory_kb\":%llu,"
             "\"memory_usage_pct\":%.2f,"
             "\"disk_total_kb\":%llu,"
             "\"disk_free_kb\":%llu,"
             "\"disk_used_kb\":%llu,"
             "\"disk_usage_pct\":%.2f,"
             "\"system_uptime_sec\":%llu"
             "},"
             "\"collection\":{"
             "\"interval_sec\":%d,"
             "\"last_collect_time\":%llu,"
             "\"history_count\":%zu"
             "}"
             "}",
             platform_name, (unsigned long long)service_uptime,
             (unsigned long long)svc->request_count, (unsigned long long)svc->error_count,
             last_collect > 0 ? "true" : "false", snap.cpu_cores, snap.cpu_usage_pct,
             (unsigned long long)snap.total_memory_kb, (unsigned long long)snap.free_memory_kb,
             (unsigned long long)snap.used_memory_kb, snap.memory_usage_pct,
             (unsigned long long)snap.disk_total_kb, (unsigned long long)snap.disk_free_kb,
             (unsigned long long)snap.disk_used_kb, snap.disk_usage_pct,
             (unsigned long long)snap.uptime_sec, INFO_D_COLLECT_INTERVAL_SEC,
             (unsigned long long)last_collect, svc->history_count);

    airy_sock_send(client_fd, response, strlen(response));
    airy_sock_close(client_fd);
}

int main(int argc __attribute__((unused)), char **argv __attribute__((unused)))
{

#ifdef _WIN32
    SetConsoleCtrlHandler(NULL, TRUE);
#else
    signal(SIGINT, info_d_signal_handler);
    signal(SIGTERM, info_d_signal_handler);
    signal(SIGPIPE, SIG_IGN);
    signal(SIGUSR1, svc_log_toggle_handler);
#endif

    airy_log_init(NULL);
    atexit(log_cleanup);

    daemon_cupolas_init("info_d");

    if (info_d_init(&g_service, INFO_D_DEFAULT_PORT, INFO_D_DEFAULT_SOCKET) != AIRY_SUCCESS)
        return EXIT_FAILURE;
    if (info_d_start(&g_service) != AIRY_SUCCESS) {
        info_d_destroy(&g_service);
        return EXIT_FAILURE;
    }

    g_bsd = daemon_bootstrap_sd_start("info_d", "info", g_service.socket_path, 0, "info,core", 0);
    g_bipc = daemon_bootstrap_ipc_start("info_d", "info", g_service.socket_path, 0,
                                        IPC_BUS_PROTO_JSON_RPC);

    g_event_loop = airy_event_loop_create(64);
    if (!g_event_loop) {
        LOG_ERROR("Failed to create event loop");
        info_d_stop(&g_service, 1);
        info_d_destroy(&g_service);
        return EXIT_FAILURE;
    }

    airy_event_loop_add_fd(g_event_loop, (int)g_service.server_fd, AIRY_EVENT_TYPE_READ,
                           info_d_on_client, &g_service);

    LOG_INFO("info_d running with epoll event loop on fd=%d", (int)g_service.server_fd);
    airy_event_loop_run(g_event_loop);

    airy_event_loop_destroy(g_event_loop);
    g_event_loop = NULL;

    daemon_bootstrap_ipc_stop(g_bipc);
    daemon_bootstrap_sd_stop(g_bsd);
    info_d_stop(&g_service, g_shutdown ? 1 : 0);
    info_d_destroy(&g_service);
    daemon_cupolas_cleanup();
    log_cleanup();
    return 0;
}
