// SPDX-FileCopyrightText: 2025-2026 SPHARX Ltd.
// SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0

#include "airy_memory.h"
#include "error.h"
/*
 * P0.18.1: daemon_main.h transitively provides atomic_compat,
 * daemon_bootstrap_sd/ipc, daemon_cupolas, daemon_platform_ext, logging,
 * svc_logger headers. This daemon uses a custom WebSocket/SSE broadcast
 * engine and accept loop; it does not use the JSON-RPC boilerplate
 * generated by DAEMON_DECLARE_COMMON. The service core (subscription
 * registry / event queue / broadcast engine / JSON-RPC dispatch) lives in
 * notify_service.c.
 */

#include "daemon_main.h"
#include "notify_service.h"
#include "platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef _WIN32
#include <arpa/inet.h>
#include <netinet/in.h>
#include <poll.h>
#include <sys/socket.h>
#include <unistd.h>
#endif

#define NOTIFY_D_DEFAULT_PORT 8084
#define NOTIFY_D_DEFAULT_SOCKET airy_runtime_dir_socket("notify.sock")
#define NOTIFY_D_WS_GUID "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

static notify_d_service_t g_service = {0};
static atomic_int g_shutdown = 0;
/* 并发连接上限：每连接一线程，无上限时恶意连接风暴可耗尽线程资源
 * （工业场景 DoS 防护）。超过上限的新连接直接关闭。 */
#define NOTIFY_D_MAX_CONN 128
static atomic_int g_conns = 0;
static daemon_bootstrap_sd_t *g_bsd = NULL;
static daemon_bootstrap_ipc_t *g_bipc = NULL;

static void notify_d_signal_handler(int sig)
{
    (void)sig;

    atomic_store_explicit(&g_shutdown, 1, memory_order_seq_cst);
#ifndef _WIN32
    {
        static const char sig_msg[] =
            "[SIG] shutdown signal received, initiating graceful shutdown\n";
        (void)write(STDERR_FILENO, sig_msg, sizeof(sig_msg) - 1);
    }
#endif
}

static int notify_ws_accept_key(const char *client_key, char *out_key, size_t out_size)
{
    if (!client_key || !out_key || out_size < 64) {
        AIRY_ERROR(AIRY_ERR_INVALID_PARAM, "null parameter");
    }

    char combined[256];
    snprintf(combined, sizeof(combined), "%s%s", client_key, NOTIFY_D_WS_GUID);

    unsigned char sha1[20];
    __builtin_memset(sha1, 0, sizeof(sha1));

    unsigned int h0 = 0x67452301, h1 = 0xEFCDAB89, h2 = 0x98BADCFE;
    unsigned int h3 = 0x10325476, h4 = 0xC3D2E1F0;

    size_t msg_len = strlen(combined);
    size_t padded_len = ((msg_len + 8) / 64 + 1) * 64;
    unsigned char *padded = (unsigned char *)AIRY_CALLOC(1, padded_len);
    if (!padded) {
        AIRY_ERROR(AIRY_ERR_OUT_OF_MEMORY, "calloc failed for SHA1 padded buffer");
    }
    __builtin_memcpy(padded, combined, msg_len);
    padded[msg_len] = 0x80;

    uint64_t bit_len = (uint64_t)msg_len * 8;
    for (int i = 0; i < 8; i++)
        padded[padded_len - 8 + i] = (unsigned char)(bit_len >> (56 - 8 * i));

    for (size_t off = 0; off < padded_len; off += 64) {
        unsigned int w[80];
        for (int i = 0; i < 16; i++) {
            w[i] = ((unsigned int)padded[off + i * 4] << 24) |
                   ((unsigned int)padded[off + i * 4 + 1] << 16) |
                   ((unsigned int)padded[off + i * 4 + 2] << 8) |
                   ((unsigned int)padded[off + i * 4 + 3]);
        }
        for (int i = 16; i < 80; i++) {
            w[i] = (w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]);
            w[i] = (w[i] << 1) | (w[i] >> 31);
        }
        unsigned int a = h0, b = h1, c = h2, d = h3, e = h4;
        for (int i = 0; i < 80; i++) {
            unsigned int f, k;
            if (i < 20) {
                f = (b & c) | (~b & d);
                k = 0x5A827999;
            } else if (i < 40) {
                f = b ^ c ^ d;
                k = 0x6ED9EBA1;
            } else if (i < 60) {
                f = (b & c) | (b & d) | (c & d);
                k = 0x8F1BBCDC;
            } else {
                f = b ^ c ^ d;
                k = 0xCA62C1D6;
            }
            unsigned int temp = ((a << 5) | (a >> 27)) + f + e + k + w[i];
            e = d;
            d = c;
            c = (b << 30) | (b >> 2);
            b = a;
            a = temp;
        }
        h0 += a;
        h1 += b;
        h2 += c;
        h3 += d;
        h4 += e;
    }
    AIRY_FREE(padded);
    padded = NULL;

    sha1[0] = (unsigned char)(h0 >> 24);
    sha1[1] = (unsigned char)(h0 >> 16);
    sha1[2] = (unsigned char)(h0 >> 8);
    sha1[3] = (unsigned char)(h0);
    sha1[4] = (unsigned char)(h1 >> 24);
    sha1[5] = (unsigned char)(h1 >> 16);
    sha1[6] = (unsigned char)(h1 >> 8);
    sha1[7] = (unsigned char)(h1);
    sha1[8] = (unsigned char)(h2 >> 24);
    sha1[9] = (unsigned char)(h2 >> 16);
    sha1[10] = (unsigned char)(h2 >> 8);
    sha1[11] = (unsigned char)(h2);
    sha1[12] = (unsigned char)(h3 >> 24);
    sha1[13] = (unsigned char)(h3 >> 16);
    sha1[14] = (unsigned char)(h3 >> 8);
    sha1[15] = (unsigned char)(h3);
    sha1[16] = (unsigned char)(h4 >> 24);
    sha1[17] = (unsigned char)(h4 >> 16);
    sha1[18] = (unsigned char)(h4 >> 8);
    sha1[19] = (unsigned char)(h4);

    static const char *b64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    size_t off = 0;

    for (int i = 0; i < 18 && off + 4 <= out_size; i += 3) {
        unsigned int val = ((unsigned int)sha1[i] << 16) | ((unsigned int)sha1[i + 1] << 8) |
                           (unsigned int)sha1[i + 2];
        out_key[off++] = b64[(val >> 18) & 0x3F];
        out_key[off++] = b64[(val >> 12) & 0x3F];
        out_key[off++] = b64[(val >> 6) & 0x3F];
        out_key[off++] = b64[val & 0x3F];
    }

    if (off + 4 <= out_size) {
        unsigned int val = ((unsigned int)sha1[18] << 16) | ((unsigned int)sha1[19] << 8);
        out_key[off++] = b64[(val >> 18) & 0x3F];
        out_key[off++] = b64[(val >> 12) & 0x3F];
        out_key[off++] = b64[(val >> 6) & 0x3F];
        out_key[off++] = '=';
    }
    out_key[off] = '\0';

    return 0;
}

static int notify_d_handle_ws_upgrade(notify_d_service_t *svc, notify_client_t *client,
                                      const char *request)
{
    (void)svc;
    const char *key_tag = "Sec-WebSocket-Key: ";
    const char *key_start = strstr(request, key_tag);
    if (!key_start) {
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "missing Sec-WebSocket-Key header");
    }
    key_start += strlen(key_tag);

    const char *key_end = strstr(key_start, "\r\n");
    if (!key_end) {
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "Sec-WebSocket-Key value not terminated by CRLF");
    }

    char client_key[256];
    size_t key_len = (size_t)(key_end - key_start);
    if (key_len >= sizeof(client_key)) {
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "Sec-WebSocket-Key too long");
    }
    __builtin_memcpy(client_key, key_start, key_len);
    client_key[key_len] = '\0';

    char accept_key[64];
    if (notify_ws_accept_key(client_key, accept_key, sizeof(accept_key)) != 0) {
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to compute WebSocket accept key");
    }

    char response[1024];
    int resp_len = snprintf(response, sizeof(response),
                            "HTTP/1.1 101 Switching Protocols\r\n"
                            "Upgrade: websocket\r\n"
                            "Connection: Upgrade\r\n"
                            "Sec-WebSocket-Accept: %s\r\n"
                            "\r\n",
                            accept_key);

    if (airy_sock_send(client->fd, response, (size_t)resp_len) <= 0) {
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to send WebSocket 101 response");
    }

    client->type = NOTIFY_CLIENT_WEBSOCKET;
    client->handshake_done = 1;
    return 0;
}

#ifndef _WIN32
static void *notify_d_event_loop(void *arg)
{
#else
static DWORD WINAPI notify_d_event_loop(LPVOID arg)
{
#endif
    notify_d_service_t *svc = (notify_d_service_t *)arg;
    if (!svc) {
#ifndef _WIN32
        AIRY_ERROR_NULL(AIRY_ERR_INVALID_PARAM, "null parameter");
#else
        return EXIT_FAILURE;
#endif
    }

    while (svc->event_running) {
        airy_mtx_lock(&svc->lock);

        if (svc->pending_count > 0) {
            notify_event_t *event = svc->pending[svc->pending_head];
            svc->pending_head = (svc->pending_head + 1) % NOTIFY_D_MAX_PENDING;
            svc->pending_count--;

            airy_mtx_unlock(&svc->lock);

            notify_d_broadcast_event(svc, event);

            AIRY_FREE(event->message);
            AIRY_FREE(event->topic);
            AIRY_FREE(event->event_type);
            AIRY_FREE(event);
        } else {
            airy_mtx_unlock(&svc->lock);
#ifndef _WIN32

            for (int _w = 0; _w < 10 && svc->event_running; _w++) {
                usleep(100000); /* 100ms */
            }
#else

            for (int _w = 0; _w < 10 && svc->event_running; _w++) {
                Sleep(100); /* 100ms */
            }
#endif
        }
    }

#ifndef _WIN32
    return NULL;
#else
    return 0;
#endif
}

static notify_client_t *notify_d_find_client_slot(notify_d_service_t *svc)
{
    for (size_t i = 0; i < NOTIFY_D_MAX_CLIENTS; i++) {
        if (!svc->clients[i].active)
            return &svc->clients[i];
    }
    if (svc->client_count < NOTIFY_D_MAX_CLIENTS)
        return &svc->clients[svc->client_count];
    AIRY_ERROR_NULL(AIRY_ERR_INVALID_PARAM, "null parameter");
}

static int notify_d_init(notify_d_service_t *svc, int port, const char *sock)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

    if (notify_d_service_init(svc) != AIRY_SUCCESS) {
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to init notify service core");
    }
    svc->tcp_port = port > 0 ? port : NOTIFY_D_DEFAULT_PORT;
    svc->socket_path = sock ? AIRY_STRDUP(sock) : AIRY_STRDUP(NOTIFY_D_DEFAULT_SOCKET);

    airy_sock_init();

    SVC_LOG_INFO("notify_d: init complete (max_clients=%d)", NOTIFY_D_MAX_CLIENTS);
    return AIRY_SUCCESS;
}

static int notify_d_start(notify_d_service_t *svc)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

#ifndef _WIN32
    svc->server_fd = airy_sock_create_unix_server(svc->socket_path);
    if (svc->server_fd < 0) {
        SVC_LOG_ERROR("notify_d: failed to create socket at %s", svc->socket_path);
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to create unix socket");
    }
#else
    svc->server_fd = airy_sock_create_tcp_server("127.0.0.1", (uint16_t)svc->tcp_port);
    if (svc->server_fd < 0) {
        SVC_LOG_ERROR("notify_d: failed to create TCP server");
        AIRY_ERROR(AIRY_ERR_UNKNOWN, "failed to create TCP server");
    }
#endif

    svc->running = 1;
    svc->event_running = 1;
    svc->force_stop = 0;

    airy_thread_create(&svc->event_thread, notify_d_event_loop, svc);

    SVC_LOG_INFO("notify_d: service started (event_loop=active)");
    return AIRY_SUCCESS;
}

static int notify_d_stop(notify_d_service_t *svc, int force)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

    airy_mtx_lock(&svc->lock);
    svc->running = 0;
    svc->event_running = 0;
    if (force)
        svc->force_stop = 1;
    airy_mtx_unlock(&svc->lock);

    if (!force) {
        airy_thread_join(svc->event_thread, NULL);
    }

    for (size_t i = 0; i < svc->client_count; i++) {
        if (svc->clients[i].active && svc->clients[i].fd != AIRY_INVALID_SOCKET) {
            if (force) {
                airy_sock_close(svc->clients[i].fd);
                svc->clients[i].fd = AIRY_INVALID_SOCKET;
                svc->clients[i].active = 0;
            }
        }
    }

    if (force) {
        for (size_t i = 0; i < svc->pending_count; i++) {
            size_t idx = (svc->pending_head + i) % NOTIFY_D_MAX_PENDING;
            notify_event_t *event = svc->pending[idx];
            if (event) {
                AIRY_FREE(event->message);
                AIRY_FREE(event->topic);
                AIRY_FREE(event->event_type);
                AIRY_FREE(event);
            }
            svc->pending[idx] = NULL;
        }
        svc->pending_count = 0;
        svc->pending_head = 0;
        svc->pending_tail = 0;
    }

    if (svc->server_fd != AIRY_INVALID_SOCKET) {
        airy_sock_close(svc->server_fd);
        svc->server_fd = AIRY_INVALID_SOCKET;
    }

    if (force) {
#ifndef _WIN32
        unlink(svc->socket_path);
#endif
    }

    SVC_LOG_INFO("notify_d: service stopped (force=%d, pending=%zu, clients=%zu)", force,
                 svc->pending_count, svc->client_count);
    return AIRY_SUCCESS;
}

static int notify_d_destroy(notify_d_service_t *svc)
{
    if (!svc) {
        AIRY_ERROR(AIRY_EINVAL, "svc is NULL");
    }

    notify_d_stop(svc, 1);
    notify_d_service_destroy(svc);
    airy_sock_cleanup();
    AIRY_FREE(svc->socket_path);
    __builtin_memset(svc, 0, sizeof(*svc));
    SVC_LOG_INFO("notify_d: service destroyed");
    return AIRY_SUCCESS;
}

static int notify_d_healthcheck(notify_d_service_t *svc)
{
    if (!svc)
        return 0;

    airy_mtx_lock(&svc->lock);
    int healthy = svc->running && svc->event_running ? 1 : 0;
    size_t active_clients = 0;
    for (size_t i = 0; i < svc->client_count; i++) {
        if (svc->clients[i].active)
            active_clients++;
    }
    size_t pending = svc->pending_count;
    size_t error_count = svc->error_count;
    size_t notified_count = svc->notified_count;
    airy_mtx_unlock(&svc->lock);

    if (pending >= NOTIFY_D_MAX_PENDING)
        healthy = 0;
    if (error_count > notified_count / 2 && notified_count > 10)
        healthy = 0;

    return healthy;
}

static void notify_d_handle_request(notify_d_service_t *svc, airy_sock_t client_fd);

/* 连接处理线程（detached）：每连接独立处理。notify_d_handle_request 在
 * recv 前 poll 等待首包最多 5s，单线程 accept 循环下慢连接会阻塞全部
 * RPC（health_check 偶发超时，实测 max~4.5s）。SSE/WebSocket 长连接
 * 注册进 svc->clients 后由事件线程推送，与本线程无关。 */
static void *notify_d_conn_thread(void *arg)
{
    airy_sock_t client = (airy_sock_t)(intptr_t)arg;
    notify_d_handle_request(&g_service, client);
    atomic_fetch_sub_explicit(&g_conns, 1, memory_order_relaxed);
    return NULL;
}

static void notify_d_handle_request(notify_d_service_t *svc, airy_sock_t client_fd)
{
    char buffer[NOTIFY_D_MAX_BUFFER];
#ifndef _WIN32
    /* Wait for request data to be ready before recv: airy_sock_recv is a
     * non-blocking MSG_DONTWAIT read; recv immediately after accept returns 0
     * on EAGAIN and would misjudge the connection as failed and close it (RPC
     * timing race). */
    struct pollfd pfd;
    pfd.fd = (int)client_fd;
    pfd.events = POLLIN;
    pfd.revents = 0;
    int pr = poll(&pfd, 1, 5000);
    if (pr <= 0 || !(pfd.revents & POLLIN)) {
        airy_sock_close(client_fd);
        return;
    }
#endif
    ssize_t n = airy_sock_recv(client_fd, buffer, sizeof(buffer) - 1);
    if (n <= 0) {
        airy_sock_close(client_fd);
        return;
    }
    buffer[n] = '\0';

    /* L2 namespace methods (02-l2-service-protocol.md §6.1): gateway strips
     * the <ns>. prefix during forwarding, so here match publish/subscribe/
     * unsubscribe/list/health and the standard methods shutdown/get_stats/
     * health_check directly; on a hit respond with JSON-RPC 2.0; everything
     * else (SSE/WebSocket upgrade/plain message delivery) keeps the original
     * logic, backward compatible. */
    char rpc_response[NOTIFY_D_MAX_BUFFER];
    int dispatch_rc = notify_d_dispatch_jsonrpc(svc, buffer, rpc_response, sizeof(rpc_response));
    if (dispatch_rc == NOTIFY_D_METHOD_SHUTDOWN) {

        atomic_store_explicit(&g_shutdown, 1, memory_order_seq_cst);
    }
    if (dispatch_rc == NOTIFY_D_METHOD_HANDLED || dispatch_rc == NOTIFY_D_METHOD_SHUTDOWN) {
        airy_sock_send(client_fd, rpc_response, strlen(rpc_response));
        airy_sock_close(client_fd);
        return;
    }

    airy_mtx_lock(&svc->lock);

    int is_upgrade = (strstr(buffer, "Upgrade: websocket") != NULL ||
                      strstr(buffer, "Upgrade: WebSocket") != NULL);
    int is_sse = (strstr(buffer, "Accept: text/event-stream") != NULL);

    notify_client_t *client = notify_d_find_client_slot(svc);
    if (!client) {
        airy_mtx_unlock(&svc->lock);
        const char *busy = "{\"error\":\"max_clients_reached\"}";
        airy_sock_send(client_fd, busy, strlen(busy));
        airy_sock_close(client_fd);
        return;
    }

    __builtin_memset(client, 0, sizeof(*client));
    client->fd = client_fd;
    client->connected_at = (uint64_t)time(NULL);
    client->last_activity = client->connected_at;
    client->active = 1;

    const char *cid_tag = "X-Client-Id: ";
    const char *cid_hdr = strstr(buffer, cid_tag);
    if (cid_hdr) {
        const char *cid_start = cid_hdr + strlen(cid_tag);
        const char *cid_end = strstr(cid_start, "\r\n");
        if (cid_end && cid_end > cid_start) {
            size_t clen = (size_t)(cid_end - cid_start);
            if (clen > 0 && clen < 256) {
                char *cid = (char *)AIRY_MALLOC(clen + 1);
                if (cid) {
                    __builtin_memcpy(cid, cid_start, clen);
                    cid[clen] = '\0';
                    client->client_id = cid;
                }
            }
        }
    }

    if (is_sse) {
        client->type = NOTIFY_CLIENT_SSE;
        const char *sse_headers = "HTTP/1.1 200 OK\r\n"
                                  "Content-Type: text/event-stream\r\n"
                                  "Cache-Control: no-cache\r\n"
                                  "Connection: keep-alive\r\n"
                                  "\r\n";
        airy_sock_send(client_fd, sse_headers, strlen(sse_headers));
        client->handshake_done = 1;
        svc->client_count++;
    } else if (is_upgrade) {
        client->type = NOTIFY_CLIENT_WEBSOCKET;
        if (notify_d_handle_ws_upgrade(svc, client, buffer) == 0) {
            svc->client_count++;
        } else {
            client->active = 0;
            airy_mtx_unlock(&svc->lock);
            airy_sock_close(client_fd);
            return;
        }
    } else {
        client->type = NOTIFY_CLIENT_SOCKET;

        const char *topic = "inbound";
        const char *topic_hdr = "X-Topic: ";
        const char *th = strstr(buffer, topic_hdr);
        if (th) {
            const char *the = strstr(th + strlen(topic_hdr), "\r\n");
            if (the) {
                size_t tlen = (size_t)(the - (th + strlen(topic_hdr)));
                char *tn = (char *)AIRY_MALLOC(tlen + 1);
                if (tn) {
                    __builtin_memcpy(tn, th + strlen(topic_hdr), tlen);
                    tn[tlen] = '\0';
                    topic = tn;
                }
            }
        }
        client->topic = AIRY_STRDUP(topic);
        if (strcmp(topic, "inbound") != 0)
            AIRY_FREE((void *)topic);
        svc->client_count++;

        int ret = notify_d_enqueue(svc, buffer, client->topic, NULL);
        if (ret == 0) {
            svc->notified_count++;
        } else {
            svc->error_count++;
        }
    }

    uint64_t uptime = (uint64_t)time(NULL) - svc->start_time;
    size_t active_clients = 0;
    for (size_t i = 0; i < svc->client_count; i++) {
        if (svc->clients[i].active)
            active_clients++;
    }

    size_t depth = svc->pending_count;
    airy_mtx_unlock(&svc->lock);

    if (client->type == NOTIFY_CLIENT_SOCKET) {
        char response[4096];
        snprintf(response, sizeof(response),
                 "{"
                 "\"service\":\"notify_d\","
                 "\"status\":\"%s\","
                 "\"queued\":%llu,"
                 "\"pending\":%zu,"
                 "\"active_clients\":%zu,"
                 "\"uptime_sec\":%llu,"
                 "\"healthy\":%s"
                 "}",
                 svc->error_count > svc->notified_count / 2 ? "degraded" : "ok",
                 (unsigned long long)svc->notified_count, depth, active_clients,
                 (unsigned long long)uptime, notify_d_healthcheck(svc) ? "true" : "false");

        airy_sock_send(client_fd, response, strlen(response));
        airy_sock_close(client_fd);

        airy_mtx_lock(&svc->lock);
        client->active = 0;
        client->fd = AIRY_INVALID_SOCKET;
        airy_mtx_unlock(&svc->lock);
    }
}

int main(int argc __attribute__((unused)), char **argv __attribute__((unused)))
{

#ifndef _WIN32
    signal(SIGINT, notify_d_signal_handler);
    signal(SIGTERM, notify_d_signal_handler);
    signal(SIGPIPE, SIG_IGN);
#endif

    airy_log_init(NULL);
    atexit(log_cleanup);

    daemon_cupolas_init_pep("notify_d");

    if (notify_d_init(&g_service, NOTIFY_D_DEFAULT_PORT, NOTIFY_D_DEFAULT_SOCKET) != AIRY_SUCCESS)
        return EXIT_FAILURE;
    if (notify_d_start(&g_service) != AIRY_SUCCESS) {
        notify_d_destroy(&g_service);
        return EXIT_FAILURE;
    }

    g_bsd =
        daemon_bootstrap_sd_start("notify_d", "notify", g_service.socket_path, 0, "notify,core", 0);
    g_bipc = daemon_bootstrap_ipc_start("notify_d", "notify", g_service.socket_path, 0,
                                        IPC_BUS_PROTO_JSON_RPC);

    while (!g_shutdown && g_service.running) {
        airy_sock_t client = airy_sock_accept(g_service.server_fd, 1000);
        if (client != AIRY_INVALID_SOCKET) {
            if (atomic_load_explicit(&g_conns, memory_order_relaxed) >= NOTIFY_D_MAX_CONN) {
                airy_sock_close(client); /* 过载：拒绝新连接 */
                continue;
            }
            atomic_fetch_add_explicit(&g_conns, 1, memory_order_relaxed);
            airy_thread_t th;
            if (airy_thread_create(&th, notify_d_conn_thread, (void *)(intptr_t)client) == 0)
                airy_thread_detach(th);
            else {
                atomic_fetch_sub_explicit(&g_conns, 1, memory_order_relaxed);
                airy_sock_close(client);
            }
        }
    }

    daemon_bootstrap_ipc_stop(g_bipc);
    daemon_bootstrap_sd_stop(g_bsd);
    notify_d_stop(&g_service, g_shutdown ? 1 : 0);
    notify_d_destroy(&g_service);
    daemon_cupolas_cleanup();
    log_cleanup();
    return 0;
}
