/* SPDX-FileCopyrightText: 2025-2026 SPHARX Ltd. */
/* SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0 */

/**
 * @file cupolas_service.h
 * @brief Public cupolas security-dome service interface (cupolas.* ns).
 *
 * cupolas_d wraps the cupolas security library (permission engine / input
 * sanitization / audit / workbench) into a standalone daemon service,
 * exposing the cupolas.* namespace over a Unix-socket JSON-RPC.
 *
 * Exposed methods:
 *   - cupolas.check_permission : permission decision
 *   - cupolas.sanitize         : input sanitization
 *   - cupolas.execute_command  : isolated workbench command execution
 *   - cupolas.add_rule         : dynamically add a permission rule
 *   - cupolas.audit_flush      : flush audit logs
 *   - cupolas.get_stats        : service stats (real counters)
 *   - cupolas.shutdown         : graceful exit (generated by main.c macro)
 *
 * This interface defines the service lifecycle, method parameter structs
 * and result structs. The implementation lives in src/service.c; all
 * methods really call the agentrt/cupolas/include/cupolas.h API.
 */

#ifndef AIRY_RT_DAEMON_CUPOLAS_SERVICE_H
#define AIRY_RT_DAEMON_CUPOLAS_SERVICE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct cupolas_service cupolas_service_t;


typedef struct {
    const char *agent_id;
    const char *action;
    const char *resource;
    const char *context;
} cupolas_check_permission_params_t;


typedef struct {
    const char *input;
} cupolas_sanitize_params_t;


typedef struct {
    const char *command;
    char **argv;
} cupolas_execute_command_params_t;


typedef struct {
    const char *agent_id;
    const char *action;
    const char *resource;
    int allow;
    int priority;
} cupolas_add_rule_params_t;


typedef struct {
    int allowed;
    int err;
} cupolas_check_permission_result_t;


typedef struct {
    char *sanitized;
    int err;
} cupolas_sanitize_result_t;


typedef struct {
    int exit_code;
    char *stdout_buf;
    char *stderr_buf;
    int err;
} cupolas_execute_command_result_t;


typedef struct {
    int added;
    int err;
} cupolas_add_rule_result_t;


/* ==================== Credential vault (cupolas.vault_*) ==================== */

typedef struct {
    const char *cred_id;
    int cred_type; /* cupolas_vault_cred_type_t */
    const uint8_t *data;
    size_t data_len;
    const char *agent_id;
} cupolas_vault_store_params_t;

typedef struct {
    int stored;
    int err;
} cupolas_vault_store_result_t;

typedef struct {
    const char *cred_id;
    const char *agent_id;
} cupolas_vault_retrieve_params_t;

typedef struct {
    uint8_t *data; /* freed via cupolas_vault_retrieve_result_free */
    size_t data_len;
    int err;
} cupolas_vault_retrieve_result_t;

typedef struct {
    const char *cred_id;
    const char *agent_id;
} cupolas_vault_delete_params_t;

typedef struct {
    int deleted;
    int err;
} cupolas_vault_delete_result_t;

typedef struct {
    const char *cred_group;
    int strategy; /* cupolas_vault_rotation_strategy_t */
} cupolas_vault_rotate_params_t;

typedef struct {
    char *selected_id; /* caller AIRY_FREEs */
    int err;
} cupolas_vault_rotate_result_t;


/* ==================== Network rules (cupolas.net_*) ==================== */

typedef struct {
    const char *rule_id;
    const char *description;
    const char *src_ip;
    const char *dst_ip;
    const char *src_port;
    const char *dst_port;
    int protocol;  /* cupolas_proto_t */
    int direction; /* cupolas_direction_t */
    int action;    /* cupolas_fw_action_t */
    int priority;
} cupolas_net_add_rule_params_t;

typedef struct {
    int added;
    int err;
} cupolas_net_add_rule_result_t;

typedef struct {
    const char *host;
    uint16_t port;
    int protocol;      /* cupolas_proto_t */
    const char *direction; /* "inbound" / "outbound" */
} cupolas_net_check_access_params_t;

typedef struct {
    int allowed;
    int err;
} cupolas_net_check_access_result_t;


/* ==================== Entitlements (cupolas.entitlements_*) ==================== */

typedef struct {
    const char *yaml_path;
} cupolas_entitlements_load_params_t;

typedef struct {
    int loaded;
    int err;
} cupolas_entitlements_load_result_t;

typedef struct {
    const char *kind; /* "fs" | "net" | "ipc" | "syscall" | "capability" | "vault" */
    const char *param1;
    const char *param2;
} cupolas_entitlements_check_params_t;

typedef struct {
    int allowed;
    int err;
} cupolas_entitlements_check_result_t;


/**
 * @brief Create a cupolas service instance.
 * @param config_path cupolas config file path (NULL = default config)
 * @return Service instance, NULL on failure
 * @note cupolas is a process-level singleton library (cupolas_init); this
 *       instance only carries stats and config metadata. Actual module init
 *       is done by daemon_cupolas_init() in main().
 */
cupolas_service_t *cupolas_service_create(const char *config_path);

/**
 * @brief Destroy a cupolas service instance.
 * @param svc Service instance (may be NULL)
 */
void cupolas_service_destroy(cupolas_service_t *svc);


/**
 * @brief Permission decision: check whether a subject may perform an action
 *        on a resource.
 * @return AIRY_SUCCESS on success; *out holds the allow result; else error code
 */
int cupolas_service_check_permission(cupolas_service_t *svc,
                                     const cupolas_check_permission_params_t *params,
                                     cupolas_check_permission_result_t *out);

/**
 * @brief Input sanitization: sanitize an input string (HTML/SQL/Shell
 *        injection protection).
 * @return AIRY_SUCCESS on success (sanitized or passed through), *out holds
 *         the result; else error code
 */
int cupolas_service_sanitize(cupolas_service_t *svc, const cupolas_sanitize_params_t *params,
                             cupolas_sanitize_result_t *out);

/**
 * @brief Isolated workbench command execution: run a command in the cupolas
 *        workbench.
 * @return AIRY_SUCCESS on success (regardless of command exit code), *out
 *         holds the exit code and output; else error code
 */
int cupolas_service_execute_command(cupolas_service_t *svc,
                                    const cupolas_execute_command_params_t *params,
                                    cupolas_execute_command_result_t *out);

/**
 * @brief Dynamically add a permission rule.
 * @return AIRY_SUCCESS on success, *out holds the add result; else error code
 */
int cupolas_service_add_rule(cupolas_service_t *svc, const cupolas_add_rule_params_t *params,
                             cupolas_add_rule_result_t *out);

/**
 * @brief Flush audit logs (persist all pending audit records).
 * @return AIRY_SUCCESS on success
 */
int cupolas_service_audit_flush(cupolas_service_t *svc);

/**
 * @brief Get the service-stats JSON string (real stats: version/uptime/
 *        permission-check count/sanitize count).
 * @return JSON string (caller AIRY_FREEs), NULL on failure
 */
char *cupolas_service_get_stats_json(cupolas_service_t *svc);


void cupolas_sanitize_result_free(cupolas_sanitize_result_t *out);
void cupolas_execute_command_result_free(cupolas_execute_command_result_t *out);


/* ==================== Credential-vault service methods ==================== */

int cupolas_service_vault_store(cupolas_service_t *svc, const cupolas_vault_store_params_t *params,
                                cupolas_vault_store_result_t *out);
int cupolas_service_vault_retrieve(cupolas_service_t *svc,
                                   const cupolas_vault_retrieve_params_t *params,
                                   cupolas_vault_retrieve_result_t *out);
void cupolas_vault_retrieve_result_free(cupolas_vault_retrieve_result_t *out);
int cupolas_service_vault_delete(cupolas_service_t *svc,
                                 const cupolas_vault_delete_params_t *params,
                                 cupolas_vault_delete_result_t *out);
int cupolas_service_vault_rotate(cupolas_service_t *svc,
                                 const cupolas_vault_rotate_params_t *params,
                                 cupolas_vault_rotate_result_t *out);
char *cupolas_service_vault_list_json(cupolas_service_t *svc, int cred_type);


/* ==================== Network-rule service methods ==================== */

int cupolas_service_net_add_rule(cupolas_service_t *svc,
                                 const cupolas_net_add_rule_params_t *params,
                                 cupolas_net_add_rule_result_t *out);
int cupolas_service_net_check_access(cupolas_service_t *svc,
                                     const cupolas_net_check_access_params_t *params,
                                     cupolas_net_check_access_result_t *out);
char *cupolas_service_net_get_stats_json(cupolas_service_t *svc);


/* ==================== Entitlements service methods ==================== */

int cupolas_service_entitlements_load(cupolas_service_t *svc,
                                      const cupolas_entitlements_load_params_t *params,
                                      cupolas_entitlements_load_result_t *out);
int cupolas_service_entitlements_check(cupolas_service_t *svc,
                                       const cupolas_entitlements_check_params_t *params,
                                       cupolas_entitlements_check_result_t *out);

#ifdef __cplusplus
}
#endif

#endif /* AIRY_RT_DAEMON_CUPOLAS_SERVICE_H */
