// SPDX-FileCopyrightText: 2026 SPHARX Ltd.
// SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0
/**
 * @file error.h
 * @brief 错误处理兼容层
 *
 * 本文件是 agentrt/commons/utils/error 的兼容层，提供向后兼容的 API。
 * 新代码应直接使用 #include <error.h>
 *
 * @see agentrt/commons/utils/error/include/error.h
 */

#ifndef AGENTRT_DAEMON_COMMON_ERROR_H
#define AGENTRT_DAEMON_COMMON_ERROR_H

/* 包含 commons 的统一错误处理框架 */
/* 使用相对路径避免 include 搜索找到 daemon 自身的 error.h */
#include "../../../commons/utils/error/include/error.h"

/* ==================== 兼容性别名 ==================== */

/* 旧的错误码名称映射到新的名称 */
#define AGENTRT_ERROR_UNKNOWN AGENTRT_ERR_UNKNOWN
#define AGENTRT_ERROR_OUT_OF_MEMORY AGENTRT_ERR_OUT_OF_MEMORY
#define AGENTRT_ERROR_INVALID_PARAMETER AGENTRT_ERR_INVALID_PARAM
#define AGENTRT_ERROR_NULL_POINTER AGENTRT_ERR_NULL_POINTER
#define AGENTRT_ERROR_BUFFER_TOO_SMALL AGENTRT_ERR_BUFFER_TOO_SMALL
#define AGENTRT_ERROR_NOT_FOUND AGENTRT_ERR_NOT_FOUND
#define AGENTRT_ERROR_ALREADY_EXISTS AGENTRT_ERR_ALREADY_EXISTS
#define AGENTRT_ERROR_TIMEOUT AGENTRT_ERR_TIMEOUT
#define AGENTRT_ERROR_NOT_SUPPORTED AGENTRT_ERR_NOT_SUPPORTED
#define AGENTRT_ERROR_PERMISSION_DENIED AGENTRT_ERR_PERMISSION_DENIED
#define AGENTRT_ERROR_IO_ERROR AGENTRT_ERR_IO
#define AGENTRT_ERROR_PARSE_ERROR AGENTRT_ERR_PARSE_ERROR
#define AGENTRT_ERROR_STATE_ERROR AGENTRT_ERR_STATE_ERROR
#define AGENTRT_ERROR_OVERFLOW AGENTRT_ERR_OVERFLOW
#define AGENTRT_ERROR_UNDERFLOW AGENTRT_ERR_UNDERFLOW
#define AGENTRT_ERROR_BUSY AGENTRT_ERR_BUSY
#define AGENTRT_ERROR_CORRUPTED_DATA AGENTRT_ERR_MEM_CORRUPT
#define AGENTRT_ERROR_INTERNAL AGENTRT_ERR_UNKNOWN

/* 核心循环错误码兼容 */
#define AGENTRT_ERROR_LOOP_BASE AGENTRT_ERR_KERN_BASE
#define AGENTRT_ERROR_LOOP_CREATE_FAILED AGENTRT_ERR_KERN_TASK
#define AGENTRT_ERROR_LOOP_RUN_FAILED AGENTRT_ERR_KERN_TASK
#define AGENTRT_ERROR_LOOP_STOP_FAILED AGENTRT_ERR_KERN_TASK
#define AGENTRT_ERROR_TASK_SUBMIT_FAILED AGENTRT_ERR_KERN_TASK
#define AGENTRT_ERROR_TASK_WAIT_FAILED AGENTRT_ERR_KERN_TASK

/* 服务层错误码兼容 */
#define AGENTRT_ERROR_SERVICE_BASE AGENTRT_ERR_SVC_BASE
#define AGENTRT_ERROR_SERVICE_NOT_READY AGENTRT_ERR_SVC_NOT_READY
#define AGENTRT_ERROR_SERVICE_BUSY AGENTRT_ERR_SVC_BUSY
#define AGENTRT_ERROR_SERVICE_STOPPED AGENTRT_ERR_SVC_STOPPED
#define AGENTRT_ERROR_SERVICE_CONFIG AGENTRT_ERR_SVC_CONFIG

/* IPC 错误码兼容 */
#define AGENTRT_ERROR_IPC_BASE AGENTRT_ERR_KERN_BASE
#define AGENTRT_ERROR_IPC_CONNECT AGENTRT_ERR_KERN_IPC
#define AGENTRT_ERROR_IPC_DISCONNECT AGENTRT_ERR_KERN_IPC
#define AGENTRT_ERROR_IPC_TIMEOUT AGENTRT_ERR_TIMEOUT
#define AGENTRT_ERROR_IPC_INVALID_MSG AGENTRT_ERR_KERN_IPC
#define AGENTRT_ERROR_IPC_BUFFER_FULL AGENTRT_ERR_BUFFER_TOO_SMALL

/* LLM 服务错误码兼容 */
#define AGENTRT_ERROR_LLM_BASE AGENTRT_ERR_LLM_BASE
#define AGENTRT_ERROR_LLM_NO_PROVIDER AGENTRT_ERR_LLM_NO_PROVIDER
#define AGENTRT_ERROR_LLM_PROVIDER_FAIL AGENTRT_ERR_LLM_PROVIDER_FAIL
#define AGENTRT_ERROR_LLM_RATE_LIMIT AGENTRT_ERR_LLM_RATE_LIMIT
#define AGENTRT_ERROR_LLM_CONTEXT_LEN AGENTRT_ERR_LLM_CONTEXT_LEN
#define AGENTRT_ERROR_LLM_INVALID_MODEL AGENTRT_ERR_LLM_INVALID_MODEL
#define AGENTRT_ERROR_LLM_AUTH_FAIL AGENTRT_ERR_LLM_AUTH_FAIL

/* 工具服务错误码兼容 */
#define AGENTRT_ERROR_TOOL_BASE AGENTRT_ERR_EXEC_BASE
#define AGENTRT_ERROR_TOOL_NOT_FOUND AGENTRT_ERR_EXEC_NOT_FOUND
#define AGENTRT_ERROR_TOOL_EXEC_FAIL AGENTRT_ERR_EXEC_FAIL
#define AGENTRT_ERROR_TOOL_TIMEOUT AGENTRT_ERR_EXEC_TIMEOUT
#define AGENTRT_ERROR_TOOL_VALIDATION AGENTRT_ERR_EXEC_VALIDATION
#define AGENTRT_ERROR_TOOL_SANDBOX AGENTRT_ERR_EXEC_SANDBOX

/* 调度服务错误码兼容 */
#define AGENTRT_ERROR_SCHED_BASE AGENTRT_ERR_KERN_BASE
#define AGENTRT_ERROR_SCHED_NO_AGENT AGENTRT_ERR_KERN_SCHED
#define AGENTRT_ERROR_SCHED_AGENT_BUSY AGENTRT_ERR_SVC_BUSY
#define AGENTRT_ERROR_SCHED_STRATEGY AGENTRT_ERR_KERN_SCHED
#define AGENTRT_ERROR_SCHED_AGENT_NOT_FOUND AGENTRT_ERR_NOT_FOUND
#define AGENTRT_ERROR_SCHED_NO_AVAILABLE AGENTRT_ERR_KERN_SCHED

/* 市场服务错误码兼容 */
#define AGENTRT_ERROR_MARKET_BASE AGENTRT_ERR_SVC_BASE
#define AGENTRT_ERROR_MARKET_NOT_FOUND AGENTRT_ERR_NOT_FOUND
#define AGENTRT_ERROR_MARKET_INSTALL AGENTRT_ERR_EXEC_FAIL
#define AGENTRT_ERROR_MARKET_DEPENDENCY AGENTRT_ERR_SVC_DEPENDENCY

/* 监控服务错误码兼容 */
#define AGENTRT_ERROR_MONITOR_BASE AGENTRT_ERR_SVC_BASE
#define AGENTRT_ERROR_MONITOR_METRIC AGENTRT_ERR_SYS_RESOURCE
#define AGENTRT_ERROR_MONITOR_TRACE AGENTRT_ERR_SYS_RESOURCE
#define AGENTRT_ERROR_MONITOR_ALERT AGENTRT_ERR_SYS_RESOURCE

/* Daemon 服务层错误码（commons 未定义，daemon 模块扩展）
 * P0.17 阶段 2：已迁移至独立的 daemon_errors.h 头文件，
 * 错误码段从 -900 迁移至 -910（消除与 commons AGENTRT_ERR_PROTOCOL 的冲突）。
 * daemons 内部源文件可直接 #include "daemon_errors.h" 获取这些错误码。 */
#include "daemon_errors.h"

/* ==================== 兼容性函数别名 ==================== */

/**
 * @brief 兼容旧函数名
 * @deprecated 请使用 agentrt_error_str
 */
#define agentrt_strerror(code) agentrt_error_str(code)

/**
 * @brief 兼容旧函数名
 * @deprecated 请使用 agentrt_error_str
 */
#define agentrt_error_name(code) agentrt_error_str(code)

/* ==================== 兼容性宏 ==================== */

/**
 * @brief 错误码检查宏（兼容旧代码）
 */
#define AGENTRT_IS_ERROR(code) ((code) != AGENTRT_OK)
#define AGENTRT_IS_SUCCESS(code) ((code) == AGENTRT_OK)

/* ==================== 兼容性类型别名 ==================== */

#endif /* AGENTRT_DAEMON_COMMON_ERROR_H */
