// SPDX-FileCopyrightText: 2026 SPHARX Ltd.
// SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0
/**
 * @file error.h
 * @brief 错误处理兼容层
 *
 * 本文件是 agentrt/commons/utils/error 的兼容层，提供向后兼容的 API。
 * 新代码应直接使用 #include <error.h>
 *
 * @see agentrt/commons/utils/error/include/error.h
 */

#ifndef AIRY_RT_DAEMON_COMMON_ERROR_H
#define AIRY_RT_DAEMON_COMMON_ERROR_H

/* 包含 commons 的统一错误处理框架 */
/* 使用相对路径避免 include 搜索找到 daemon 自身的 error.h */
#include "../../../commons/utils/error/include/error.h"

/* ==================== 兼容性别名 ==================== */

/* 旧的错误码名称映射到新的名称 */
#define AIRY_ERROR_UNKNOWN AIRY_ERR_UNKNOWN
#define AIRY_ERROR_OUT_OF_MEMORY AIRY_ERR_OUT_OF_MEMORY
#define AIRY_ERROR_INVALID_PARAMETER AIRY_ERR_INVALID_PARAM
#define AIRY_ERROR_NULL_POINTER AIRY_ERR_NULL_POINTER
#define AIRY_ERROR_BUFFER_TOO_SMALL AIRY_ERR_BUFFER_TOO_SMALL
#define AIRY_ERROR_NOT_FOUND AIRY_ERR_NOT_FOUND
#define AIRY_ERROR_ALREADY_EXISTS AIRY_ERR_ALREADY_EXISTS
#define AIRY_ERROR_TIMEOUT AIRY_ERR_TIMEOUT
#define AIRY_ERROR_NOT_SUPPORTED AIRY_ERR_NOT_SUPPORTED
#define AIRY_ERROR_PERMISSION_DENIED AIRY_ERR_PERMISSION_DENIED
#define AIRY_ERROR_IO_ERROR AIRY_ERR_IO
#define AIRY_ERROR_PARSE_ERROR AIRY_ERR_PARSE_ERROR
#define AIRY_ERROR_STATE_ERROR AIRY_ERR_STATE_ERROR
#define AIRY_ERROR_OVERFLOW AIRY_ERR_OVERFLOW
#define AIRY_ERROR_UNDERFLOW AIRY_ERR_UNDERFLOW
#define AIRY_ERROR_BUSY AIRY_ERR_BUSY
#define AIRY_ERROR_CORRUPTED_DATA AIRY_ERR_MEM_CORRUPT
#define AIRY_ERROR_INTERNAL AIRY_ERR_UNKNOWN

/* 核心循环错误码兼容 */
#define AIRY_ERROR_LOOP_BASE AIRY_ERR_KERN_BASE
#define AIRY_ERROR_LOOP_CREATE_FAILED AIRY_ERR_KERN_TASK
#define AIRY_ERROR_LOOP_RUN_FAILED AIRY_ERR_KERN_TASK
#define AIRY_ERROR_LOOP_STOP_FAILED AIRY_ERR_KERN_TASK
#define AIRY_ERROR_TASK_SUBMIT_FAILED AIRY_ERR_KERN_TASK
#define AIRY_ERROR_TASK_WAIT_FAILED AIRY_ERR_KERN_TASK

/* 服务层错误码兼容 */
#define AIRY_ERROR_SERVICE_BASE AIRY_ERR_SVC_BASE
#define AIRY_ERROR_SERVICE_NOT_READY AIRY_ERR_SVC_NOT_READY
#define AIRY_ERROR_SERVICE_BUSY AIRY_ERR_SVC_BUSY
#define AIRY_ERROR_SERVICE_STOPPED AIRY_ERR_SVC_STOPPED
#define AIRY_ERROR_SERVICE_CONFIG AIRY_ERR_SVC_CONFIG

/* IPC 错误码兼容 */
#define AIRY_ERROR_IPC_BASE AIRY_ERR_KERN_BASE
#define AIRY_ERROR_IPC_CONNECT AIRY_ERR_KERN_IPC
#define AIRY_ERROR_IPC_DISCONNECT AIRY_ERR_KERN_IPC
#define AIRY_ERROR_IPC_TIMEOUT AIRY_ERR_TIMEOUT
#define AIRY_ERROR_IPC_INVALID_MSG AIRY_ERR_KERN_IPC
#define AIRY_ERROR_IPC_BUFFER_FULL AIRY_ERR_BUFFER_TOO_SMALL

/* LLM 服务错误码兼容 */
#define AIRY_ERROR_LLM_BASE AIRY_ERR_LLM_BASE
#define AIRY_ERROR_LLM_NO_PROVIDER AIRY_ERR_LLM_NO_PROVIDER
#define AIRY_ERROR_LLM_PROVIDER_FAIL AIRY_ERR_LLM_PROVIDER_FAIL
#define AIRY_ERROR_LLM_RATE_LIMIT AIRY_ERR_LLM_RATE_LIMIT
#define AIRY_ERROR_LLM_CONTEXT_LEN AIRY_ERR_LLM_CONTEXT_LEN
#define AIRY_ERROR_LLM_INVALID_MODEL AIRY_ERR_LLM_INVALID_MODEL
#define AIRY_ERROR_LLM_AUTH_FAIL AIRY_ERR_LLM_AUTH_FAIL

/* 工具服务错误码兼容 */
#define AIRY_ERROR_TOOL_BASE AIRY_ERR_EXEC_BASE
#define AIRY_ERROR_TOOL_NOT_FOUND AIRY_ERR_EXEC_NOT_FOUND
#define AIRY_ERROR_TOOL_EXEC_FAIL AIRY_ERR_EXEC_FAIL
#define AIRY_ERROR_TOOL_TIMEOUT AIRY_ERR_EXEC_TIMEOUT
#define AIRY_ERROR_TOOL_VALIDATION AIRY_ERR_EXEC_VALIDATION
#define AIRY_ERROR_TOOL_SANDBOX AIRY_ERR_EXEC_SANDBOX

/* 调度服务错误码兼容 */
#define AIRY_ERROR_SCHED_BASE AIRY_ERR_KERN_BASE
#define AIRY_ERROR_SCHED_NO_AGENT AIRY_ERR_KERN_SCHED
#define AIRY_ERROR_SCHED_AGENT_BUSY AIRY_ERR_SVC_BUSY
#define AIRY_ERROR_SCHED_STRATEGY AIRY_ERR_KERN_SCHED
#define AIRY_ERROR_SCHED_AGENT_NOT_FOUND AIRY_ERR_NOT_FOUND
#define AIRY_ERROR_SCHED_NO_AVAILABLE AIRY_ERR_KERN_SCHED

/* 市场服务错误码兼容 */
#define AIRY_ERROR_MARKET_BASE AIRY_ERR_SVC_BASE
#define AIRY_ERROR_MARKET_NOT_FOUND AIRY_ERR_NOT_FOUND
#define AIRY_ERROR_MARKET_INSTALL AIRY_ERR_EXEC_FAIL
#define AIRY_ERROR_MARKET_DEPENDENCY AIRY_ERR_SVC_DEPENDENCY

/* 监控服务错误码兼容 */
#define AIRY_ERROR_MONITOR_BASE AIRY_ERR_SVC_BASE
#define AIRY_ERROR_MONITOR_METRIC AIRY_ERR_SYS_RESOURCE
#define AIRY_ERROR_MONITOR_TRACE AIRY_ERR_SYS_RESOURCE
#define AIRY_ERROR_MONITOR_ALERT AIRY_ERR_SYS_RESOURCE

/* Daemon 服务层错误码（commons 未定义，daemon 模块扩展）
 * P0.17 阶段 2：已迁移至独立的 daemon_errors.h 头文件，
 * 错误码段从 -900 迁移至 -910（消除与 commons AIRY_ERR_PROTOCOL 的冲突）。
 * daemons 内部源文件可直接 #include "daemon_errors.h" 获取这些错误码。 */
#include "daemon_errors.h"

/* ==================== 兼容性函数别名 ==================== */

/**
 * @brief 兼容旧函数名
 * @deprecated 请使用 airy_err_str
 */
#define airy_strerror(code) airy_err_str(code)

/**
 * @brief 兼容旧函数名
 * @deprecated 请使用 airy_err_str
 */
#define airy_err_name(code) airy_err_str(code)

/* ==================== 兼容性宏 ==================== */

/**
 * @brief 错误码检查宏（兼容旧代码）
 */
#define AIRY_IS_ERROR(code) ((code) != AIRY_OK)
#define AIRY_IS_SUCCESS(code) ((code) == AIRY_OK)

/* ==================== 兼容性类型别名 ==================== */

#endif /* AIRY_RT_DAEMON_COMMON_ERROR_H */
